import assert from "node:assert/strict";
import { findNaermesteTomtegrense, findNabotomtLabel, fitKartutsnitt, nearestPolygonBoundary, projectGarasjePunkt, unprojectGarasjePunkt } from "../apps/demo-gui/src/client/garasje-kart.ts";
import type { GarasjePolygon } from "../apps/shared/garasje.ts";
import { nearestPointOnPolygonBoundary } from "../apps/shared/geometri.ts";

const center = { lat: 60.2536577976675, lon: 5.255241147052527 };
const polygon: GarasjePolygon = {
  id: "259953783",
  ringer: [[[5.2555238, 60.2536782], [5.255341, 60.2535286], [5.2550217, 60.253501],
    [5.2548037, 60.2536077], [5.2552815, 60.2538992], [5.2555238, 60.2536782]]]
};
const rectangles: GarasjePolygon[] = [polygon, {
  id: "lang-teig",
  ringer: [[[5.25, 60.25], [5.26, 60.25], [5.26, 60.2501], [5.25, 60.2501], [5.25, 60.25]]]
}];
for (const polygons of [[polygon], rectangles, []]) {
  const bounds = fitKartutsnitt(polygons, center);
  const lonMeters = 111320 * Math.cos(center.lat * Math.PI / 180);
  const width = (bounds.east - bounds.west) * lonMeters;
  const height = (bounds.north - bounds.south) * 111320;
  assert(Math.abs(width / height - 4 / 3) < 1e-8, "Kartet må ha samme proporsjoner som SVG-flaten");
  for (const shape of polygons) {
    for (const ring of shape.ringer) {
      for (const [lon, lat] of ring) {
        assert((lon - bounds.west) * lonMeters > 9.99);
        assert((bounds.east - lon) * lonMeters > 9.99);
        assert((lat - bounds.south) * 111320 > 9.99);
        assert((bounds.north - lat) * 111320 > 9.99);
      }
    }
  }
  const [x, y] = projectGarasjePunkt(center, bounds);
  const restored = unprojectGarasjePunkt(x / 640, y / 480, bounds);
  assert(Math.abs(restored.lat - center.lat) < 1e-10);
  assert(Math.abs(restored.lon - center.lon) < 1e-10);
  assert.deepEqual(unprojectGarasjePunkt(-1, -1, bounds), { lon: bounds.west, lat: bounds.north });
  assert.deepEqual(unprojectGarasjePunkt(2, 2, bounds), { lon: bounds.east, lat: bounds.south });
}
console.log("Garasjekart: tomteutsnitt med minst ti meter marg, proporsjoner og markørplassering besto.");
const labelBounds = { west: 0, east: 640, south: 0, north: 480 };
const own = { id: "own", ringer: [[[180, 100], [460, 100], [460, 380], [180, 380], [180, 100]]] as [number, number][][] };
const surrounding = { id: "neighbour", ringer: [
  [[0, 0], [640, 0], [640, 480], [0, 480], [0, 0]],
  [[180, 100], [180, 380], [460, 380], [460, 100], [180, 100]]
] as [number, number][][] };
const label = findNabotomtLabel(surrounding, [own], labelBounds, 64, []);
assert(label);
assert(label.x < 180 || label.x > 460 || label.y < 100 || label.y > 380, "Nabonummer må ikke ligge inne på valgt tomt");
assert.equal(findNabotomtLabel(own, [own], labelBounds, 64, []), null);
const nextLabel = findNabotomtLabel(surrounding, [own], labelBounds, 64, [label]);
assert(nextLabel);
assert(Math.abs(nextLabel.x - label.x) >= 70 || Math.abs(nextLabel.y - label.y) >= 26, "Nabomerkene må ikke overlappe");
console.log("Nabomerker plasseres på riktig tomt, utenfor valgt tomt og uten overlapp.");

// Independent fixed GRS80 scales at 60 degrees; expectations are metre geometry,
// not values generated by the function under test.
const eastScale = 55800.0015731251, northScale = 111412.28745823177;
const metricPoint = (x: number, y: number) => ({ lon: 5.3 + x / eastScale, lat: 60 + y / northScale });
const metricRing = (left: number, bottom: number, right: number, top: number): [number, number][] =>
  [[left, bottom], [right, bottom], [right, top], [left, top], [left, bottom]].map(([x, y]) => {
    const p = metricPoint(x!, y!);
    return [p.lon, p.lat];
  });
const parcel: GarasjePolygon = { id: "metric-parcel", ringer: [metricRing(0, 0, 20, 10)] };
const withHole: GarasjePolygon = { id: "with-hole", ringer: [...parcel.ringer, metricRing(8, 3, 12, 7)] };
const readonlyParcels: readonly GarasjePolygon[] = [withHole];
assert.equal(nearestPolygonBoundary(metricPoint(10, 5), readonlyParcels)?.innenfor, false);
for (const [x, y, inside, distance, nearestX, nearestY] of [
  [5, 2, true, 2, 5, 0], [-3, 4, false, 3, 0, 4], [-3, -4, false, 5, 0, 0],
  [20, 6, true, 0, 20, 6], [25, 6, false, 5, 20, 6], [7, 5, true, 1, 8, 5],
  [10, 5, false, 2, null, null], [8, 5, true, 0, 8, 5],
] as const) {
  const result = findNaermesteTomtegrense(metricPoint(x, y), [withHole]);
  assert(result);
  assert.equal(result.innenfor, inside);
  assert(Math.abs(result.avstandMeter - distance) < 0.001, `Avstanden ved (${x}, ${y}) skal være ${distance} meter`);
  assert.equal(result.polygonId, "with-hole");
  if (nearestX !== null && nearestY !== null) {
    assert(Math.abs(result.punkt.lon - metricPoint(nearestX, nearestY).lon) < 1e-8);
    assert(Math.abs(result.punkt.lat - metricPoint(nearestX, nearestY).lat) < 1e-8);
  }
  if (x >= 7 && x <= 10) assert.equal(result.ringIndex, 1, "Hullgrensen må være med i nærmeste avstand");
}
const otherParcel: GarasjePolygon = { id: "other-parcel", ringer: [metricRing(30, 0, 40, 10)] };
assert.equal(findNaermesteTomtegrense(metricPoint(31, 5), [parcel, otherParcel])?.polygonId, "other-parcel");
assert.equal(findNaermesteTomtegrense(metricPoint(31, 5), [parcel, otherParcel])?.innenfor, true);
assert.equal(findNaermesteTomtegrense(metricPoint(25, 5), [parcel, otherParcel])?.innenfor, false);
assert.equal(findNaermesteTomtegrense(metricPoint(10, 5), [withHole, { id: "island", ringer: [metricRing(9, 4, 11, 6)] }])?.innenfor, true);
for (let x = -2; x <= 22; x += 2) for (let y = -2; y <= 12; y += 2) {
  const p = metricPoint(x, y);
  const result = findNaermesteTomtegrense(p, [parcel])!;
  const reverse = findNaermesteTomtegrense(p, [{ ...parcel, ringer: parcel.ringer.map(r => r.toReversed()) }])!;
  const expected = x >= 0 && x <= 20 && y >= 0 && y <= 10
    ? Math.min(x, 20 - x, y, 10 - y) : Math.hypot(Math.max(0, -x, x - 20), Math.max(0, -y, y - 10));
  assert(Math.abs(result.avstandMeter - expected) < 0.001);
  assert.equal(result.innenfor, x >= 0 && x <= 20 && y >= 0 && y <= 10);
  assert(Math.abs(result.avstandMeter - reverse.avstandMeter) < 1e-8, "Ringretningen endrer ikke avstanden");
  assert.equal(reverse.innenfor, result.innenfor);
  assert(findNaermesteTomtegrense(result.punkt, [parcel])!.avstandMeter < 1e-6, "Nærmeste punkt ligger på en kant");
}
assert.equal(findNaermesteTomtegrense(center, []), null);
for (const rings of [
  [], [[]], [metricRing(0, 0, 20, 10).slice(0, -1)],
  [[[5.3, 60], [5.3001, 60], [5.3002, 60], [5.3, 60]]],
  [[[5.3, 60], [NaN, 60], [5.3, 60.001], [5.3, 60]]],
]) {
  assert.equal(findNaermesteTomtegrense(metricPoint(1, 1), [{ id: "invalid", ringer: rings as [number, number][][] }]), null);
  assert.equal(findNaermesteTomtegrense(metricPoint(1, 1), [parcel, { id: "invalid", ringer: rings as [number, number][][] }]), null);
}
assert.equal(nearestPointOnPolygonBoundary([5.3, NaN], [parcel.ringer]), null);
assert.equal(nearestPointOnPolygonBoundary([5.3, 90], [parcel.ringer]), null);
assert.equal(nearestPointOnPolygonBoundary([10, 60], [parcel.ringer]), null);
console.log("Nærmeste kartlagte grense: meteravstand, hull, flere teiger og ukjent geometri besto. Skissepunktet er ikke bygningens utstrekning.");
